name: plus-value
favicon: null
layout_spectrum: 0.24836
typography_spectrum: 0.88103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#125160'
    - '#eeffff'
    - '#61d9f2'
    - '#fcd012'
    - '#fb5a3d'
  brandStrength: 0.47450846596620977
  lightness: 0.34723877068609
  saturation: 0.6694820579141378
  rhythmicContrast: 0.8085686729755253
purpose: []
