name: plus-value
favicon: null
layout_spectrum: 0.0029506601858884096
typography_spectrum: 0.23996204021386802
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.47450846596620977
  lightness: 0.34723877068609
  saturation: 0.6694820579141378
  rhythmicContrast: 0.8085686729755253
purpose: []
