purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5
  brandStrength: 0
  lightness: 0.5
  brandColors:
    - '#52517B'
    - '#FFFFFF'
    - '#F4973B'
    - '#B1B1C4'
    - '#010101'
  rhythmicContrast: 0.7580645
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: plus-value
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.75793
layout_spectrum: 0.688172
